package com.aes.model;
// Generated May 22, 2015 8:39:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BusinessUnit generated by hbm2java
 */
@Entity
@Table(name="business_unit"
    ,catalog="aes"
)
public class BusinessUnit  implements java.io.Serializable {


     private int businessUnitId;
     private String businessUnit;
     private Set<UserDetails> userDetailses = new HashSet<UserDetails>(0);

    public BusinessUnit() {
    }

	
    public BusinessUnit(int businessUnitId, String businessUnit) {
        this.businessUnitId = businessUnitId;
        this.businessUnit = businessUnit;
    }
    public BusinessUnit(int businessUnitId, String businessUnit, Set<UserDetails> userDetailses) {
       this.businessUnitId = businessUnitId;
       this.businessUnit = businessUnit;
       this.userDetailses = userDetailses;
    }
   
     @Id 

    
    @Column(name="businessUnitId", unique=true, nullable=false)
    public int getBusinessUnitId() {
        return this.businessUnitId;
    }
    
    public void setBusinessUnitId(int businessUnitId) {
        this.businessUnitId = businessUnitId;
    }

    
    @Column(name="businessUnit", nullable=false, length=45)
    public String getBusinessUnit() {
        return this.businessUnit;
    }
    
    public void setBusinessUnit(String businessUnit) {
        this.businessUnit = businessUnit;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="businessUnit")
    public Set<UserDetails> getUserDetailses() {
        return this.userDetailses;
    }
    
    public void setUserDetailses(Set<UserDetails> userDetailses) {
        this.userDetailses = userDetailses;
    }




}


