package com.aes.model;
// Generated May 22, 2015 8:39:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chapter generated by hbm2java
 */
@Entity
@Table(name="chapter"
    ,catalog="aes"
)
public class Chapter  implements java.io.Serializable {


     private int chapterId;
     private Course course;
     private String description;
     private int chapterNumber;
     private String chapterTitle;
     private Set<Presentation> presentations = new HashSet<Presentation>(0);

    public Chapter() {
    }

	
    public Chapter(int chapterId, Course course, String description, int chapterNumber, String chapterTitle) {
        this.chapterId = chapterId;
        this.course = course;
        this.description = description;
        this.chapterNumber = chapterNumber;
        this.chapterTitle = chapterTitle;
    }
    public Chapter(int chapterId, Course course, String description, int chapterNumber, String chapterTitle, Set<Presentation> presentations) {
       this.chapterId = chapterId;
       this.course = course;
       this.description = description;
       this.chapterNumber = chapterNumber;
       this.chapterTitle = chapterTitle;
       this.presentations = presentations;
    }
   
     @Id 

    
    @Column(name="chapterId", unique=true, nullable=false)
    public int getChapterId() {
        return this.chapterId;
    }
    
    public void setChapterId(int chapterId) {
        this.chapterId = chapterId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course_courseId", nullable=false)
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="chapterNumber", nullable=false)
    public int getChapterNumber() {
        return this.chapterNumber;
    }
    
    public void setChapterNumber(int chapterNumber) {
        this.chapterNumber = chapterNumber;
    }

    
    @Column(name="chapterTitle", nullable=false, length=50)
    public String getChapterTitle() {
        return this.chapterTitle;
    }
    
    public void setChapterTitle(String chapterTitle) {
        this.chapterTitle = chapterTitle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="chapter")
    public Set<Presentation> getPresentations() {
        return this.presentations;
    }
    
    public void setPresentations(Set<Presentation> presentations) {
        this.presentations = presentations;
    }




}


