package com.aes.model;
// Generated May 22, 2015 8:39:55 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Presentation generated by hbm2java
 */
@Entity
@Table(name="presentation"
    ,catalog="aes"
)
public class Presentation  implements java.io.Serializable {


     private int presentationId;
     private Chapter chapter;
     private String fileName;
     private String fileType;
     private double fileSize;
     private String filePath;
     private String description;
     private Date dateUploaded;
     private boolean recordStatus;

    public Presentation() {
    }

    public Presentation(int presentationId, Chapter chapter, String fileName, String fileType, double fileSize, String filePath, String description, Date dateUploaded, boolean recordStatus) {
       this.presentationId = presentationId;
       this.chapter = chapter;
       this.fileName = fileName;
       this.fileType = fileType;
       this.fileSize = fileSize;
       this.filePath = filePath;
       this.description = description;
       this.dateUploaded = dateUploaded;
       this.recordStatus = recordStatus;
    }
   
     @Id 

    
    @Column(name="presentationId", unique=true, nullable=false)
    public int getPresentationId() {
        return this.presentationId;
    }
    
    public void setPresentationId(int presentationId) {
        this.presentationId = presentationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="chapter_chapterId", nullable=false)
    public Chapter getChapter() {
        return this.chapter;
    }
    
    public void setChapter(Chapter chapter) {
        this.chapter = chapter;
    }

    
    @Column(name="fileName", nullable=false, length=45)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="fileType", nullable=false, length=45)
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    
    @Column(name="fileSize", nullable=false, precision=22, scale=0)
    public double getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(double fileSize) {
        this.fileSize = fileSize;
    }

    
    @Column(name="filePath", nullable=false)
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateUploaded", nullable=false, length=19)
    public Date getDateUploaded() {
        return this.dateUploaded;
    }
    
    public void setDateUploaded(Date dateUploaded) {
        this.dateUploaded = dateUploaded;
    }

    
    @Column(name="recordStatus", nullable=false)
    public boolean isRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(boolean recordStatus) {
        this.recordStatus = recordStatus;
    }




}


